#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────────────────
# tiktok_poster.py — TikTok auto-upload layer
#
# Uses the `tiktok-uploader` library (browser-based, no business account
# required).  Authentication is handled via a cookies file that you export
# once from a logged-in TikTok session (see README section below).
#
# Integration points:
#   • TikTokPoster.post(video_path, caption) → bool
#   • Called from agent.py immediately after a successful Telegram send so the
#     video file is guaranteed to still be on disk.
#
# Auth — two supported modes (controlled by TIKTOK_AUTH_MODE env var):
#   "cookies"  (default) — point TIKTOK_COOKIES_FILE at a Netscape-format
#              cookies.txt exported from your browser (e.g. with the
#              "Get cookies.txt LOCALLY" Chrome extension).
#   "session"  — set TIKTOK_SESSION_ID to the raw `sessionid` cookie value;
#              the poster constructs a minimal cookies file at runtime.
#
# Retry logic mirrors the Telegram notifier: up to TIKTOK_MAX_RETRIES attempts
# with exponential back-off.  Failures are logged but never raise — a TikTok
# failure must never kill a successful Telegram delivery.
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import logging
import os
import signal
import time
import tempfile
from pathlib import Path
from typing import Optional

from config import Config


# ---------------------------------------------------------------------------
# Optional import — tiktok_uploader may not be installed in all environments.
# We defer the ImportError to the first actual post() call so the agent can
# still start even when the TikTok feature is unused.
# ---------------------------------------------------------------------------
_uploader_available: bool = False
try:
    from tiktok_uploader.upload import upload_video   # type: ignore
    _uploader_available = True
except ImportError:
    pass


log = logging.getLogger("TikTokPoster")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _extract_session_id(raw: str) -> Optional[str]:
    """
    Accept either:
      - a bare session ID:          "abc123def456"
      - a full cookie string:       "sessionid=abc123; tt_csrf_token=xyz; ..."
    Returns the raw sessionid value, or None if it can't be found.
    """
    raw = raw.strip()
    if not raw:
        return None
    # If it contains '=' it's a key=value cookie string — parse it
    if "=" in raw:
        for part in raw.replace(";", " ").split():
            if part.startswith("sessionid="):
                return part.split("=", 1)[1].strip()
        return None  # sessionid not found in the string
    # Otherwise treat the whole thing as the bare session ID
    return raw


def _write_session_cookies_file(session_id: str) -> Path:
    """
    Build a minimal Netscape-format cookies file from a raw sessionid value.
    tiktok-uploader accepts this format directly.
    """
    tmp = tempfile.NamedTemporaryFile(
        suffix=".txt", prefix="tiktok_cookies_", delete=False,
    )
    tmp.write(
        b"# Netscape HTTP Cookie File\n"
        b"# Generated by tiktok_poster.py\n\n"
        b".tiktok.com\tTRUE\t/\tTRUE\t9999999999\tsessionid\t"
        + session_id.encode()
        + b"\n"
    )
    tmp.close()
    return Path(tmp.name)


def _build_caption(reel_url: str, views: int, likes: int, extra_tags: list[str]) -> str:
    """
    Construct a TikTok caption (≤ 2 200 chars).
    Uses Config.TIKTOK_CAPTION_TEMPLATE if set, otherwise a sensible default.
    """
    base_tags = " ".join(f"#{t.lstrip('#')}" for t in Config.TIKTOK_HASHTAGS)
    extra     = " ".join(f"#{t.lstrip('#')}" for t in extra_tags)
    tags_line = f"{base_tags} {extra}".strip()

    template = Config.TIKTOK_CAPTION_TEMPLATE
    if template:
        caption = (
            template
            .replace("{url}", reel_url)
            .replace("{views}", f"{views:,}")
            .replace("{likes}", f"{likes:,}")
            .replace("{tags}", tags_line)
        )
    else:
        caption = f"🎬 {tags_line}"

    # TikTok hard cap
    return caption[:2200]


# ─────────────────────────────────────────────────────────────────────────────
# TikTokPoster
# ─────────────────────────────────────────────────────────────────────────────

class TikTokPoster:
    """
    Uploads a local MP4 to TikTok.

    Lifecycle:
      1. Instantiate once on agent startup.
      2. Call post(video_path, reel_url, views, likes) after each confirmed
         Telegram send.
      3. The video file must still exist on disk when post() is called — do
         NOT let the notifier delete it until after TikTok upload.
    """

    def __init__(self) -> None:
        self.enabled: bool = Config.TIKTOK_ENABLED
        self._cookies_path: Optional[Path] = None
        self._temp_cookies: Optional[Path] = None  # auto-generated; cleaned up on close
        self._auth_mode: str = Config.TIKTOK_AUTH_MODE
        self._cleanup_done: bool = False

        if not self.enabled:
            log.info("TikTok posting disabled (TIKTOK_ENABLED=false).")
            return

        if not _uploader_available:
            log.error(
                "tiktok-uploader is not installed — TikTok posting disabled. "
                "Run: pip install tiktok-uploader"
            )
            self.enabled = False
            return

        # Auto-switch to session mode if TIKTOK_SESSION_COOKIES is set
        # and the user hasn't explicitly chosen a mode.
        if (
            (Config.TIKTOK_SESSION_COOKIES.strip() or Config.TIKTOK_SESSION_ID.strip())
            and self._auth_mode == "cookies"
            and not Path(Config.TIKTOK_COOKIES_FILE).exists()
        ):
            log.info(
                "Session cookie value is set and no cookies file found — "
                "switching to session auth mode automatically."
            )
            self._auth_mode = "session"

        self._cookies_path = self._resolve_cookies()
        if not self._cookies_path:
            log.error(
                "TikTok cookies not configured. "
                "Set TIKTOK_COOKIES_FILE or TIKTOK_SESSION_ID. "
                "TikTok posting disabled."
            )
            self.enabled = False
            return

        log.info(
            f"TikTokPoster ready (auth_mode={self._auth_mode}, "
            f"cookies={self._cookies_path})"
        )

    def __del__(self) -> None:
        self.close()

    def close(self) -> None:
        # Clean up auto-generated cookies file explicitly.
        if self._cleanup_done:
            return
        self._cleanup_done = True
        if self._temp_cookies and self._temp_cookies.exists():
            try:
                self._temp_cookies.unlink()
            except OSError:
                pass

    # ── Auth ──────────────────────────────────────────────────────────────────

    def _resolve_cookies(self) -> Optional[Path]:
        mode = self._auth_mode.lower()

        if mode == "session":
            raw = (Config.TIKTOK_SESSION_COOKIES or Config.TIKTOK_SESSION_ID).strip()
            if not raw:
                log.error("TIKTOK_AUTH_MODE=session but TIKTOK_SESSION_COOKIES/TIKTOK_SESSION_ID is empty.")
                return None
            session_id = _extract_session_id(raw)
            if not session_id:
                log.error(
                    "Could not extract sessionid from TIKTOK_SESSION_COOKIES. "
                    "Set it to either the bare sessionid value or a full cookie string "
                    "containing 'sessionid=<value>'."
                )
                return None
            path = _write_session_cookies_file(session_id)
            self._temp_cookies = path
            log.info(f"Wrote session-based cookies to {path}")
            return path

        # Default: "cookies" mode
        cookies_path = Path(Config.TIKTOK_COOKIES_FILE)
        if not cookies_path.exists():
            log.error(f"TIKTOK_COOKIES_FILE not found: {cookies_path}")
            return None
        return cookies_path

    def _upload_with_timeout(self, video_path: Path, caption: str) -> None:
        """Run upload_video with a hard timeout on Unix-like systems."""
        if Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS <= 0:
            upload_video(
                filename=str(video_path),
                description=caption,
                cookies=str(self._cookies_path),
                headless=Config.TIKTOK_HEADLESS,
                schedule=None,
            )
            return

        if not hasattr(signal, "SIGALRM"):
            upload_video(
                filename=str(video_path),
                description=caption,
                cookies=str(self._cookies_path),
                headless=Config.TIKTOK_HEADLESS,
                schedule=None,
            )
            return

        class _UploadTimeout(Exception):
            pass

        def _handler(_signum, _frame):
            raise _UploadTimeout("TikTok upload timed out")

        old_handler = signal.signal(signal.SIGALRM, _handler)
        try:
            signal.setitimer(signal.ITIMER_REAL, float(Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS))
            upload_video(
                filename=str(video_path),
                description=caption,
                cookies=str(self._cookies_path),
                headless=Config.TIKTOK_HEADLESS,
                schedule=None,
            )
        finally:
            try:
                signal.setitimer(signal.ITIMER_REAL, 0)
            except Exception:
                pass
            signal.signal(signal.SIGALRM, old_handler)

    # ── Public API ────────────────────────────────────────────────────────────

    def post(
        self,
        video_path: Path,
        reel_url: str,
        views: int = 0,
        likes: int = 0,
        extra_tags: Optional[list] = None,
    ) -> bool:
        """
        Upload *video_path* to TikTok.

        Returns True on success, False on any failure.
        Never raises — all exceptions are caught and logged.
        """
        if not self.enabled:
            return False

        if not video_path or not video_path.exists():
            log.error(f"TikTok post skipped — file not found: {video_path}")
            return False

        caption = _build_caption(reel_url, views, likes, extra_tags or [])

        for attempt in range(1, Config.TIKTOK_MAX_RETRIES + 1):
            try:
                log.info(
                    f"[TikTok] Upload attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} "
                    f"— {video_path.name}"
                )
                self._upload_with_timeout(video_path, caption)
                log.info(f"[TikTok] ✅ Upload succeeded: {video_path.name}")
                return True

            except Exception as exc:
                log.warning(
                    f"[TikTok] Upload attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} "
                    f"failed: {exc}"
                )
                if attempt < Config.TIKTOK_MAX_RETRIES:
                    sleep_s = 2 ** attempt
                    log.info(f"[TikTok] Retrying in {sleep_s}s...")
                    time.sleep(sleep_s)

        log.error(
            f"[TikTok] ❌ All {Config.TIKTOK_MAX_RETRIES} upload attempts failed "
            f"for {video_path.name}"
        )
        return False
