#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────────────────
# tiktok_poster.py — TikTok auto-upload layer
#
# Fixes applied (2026-05):
#   • NEVER force-add dot prefix to host-only cookie domains
#   • NEVER revive expired cookies with fake 2147483647 timestamp
#   • Session validation (visit /foryou, check avatar) before every upload
#   • Session-mode now writes ALL required TikTok auth cookies, not just sessionid
#   • Upload skipped (not retried) on auth-specific errors to avoid lockouts
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import logging
import os
import random
import signal
import time
import tempfile
from pathlib import Path
from typing import Optional

from config import Config


_uploader_available: bool = False
try:
    from tiktok_uploader.upload import upload_video   # type: ignore
    _uploader_available = True
except ImportError:
    pass


log = logging.getLogger("TikTokPoster")

# Errors that mean auth is broken — retrying won't help and can trigger lockouts
_AUTH_ERROR_SIGNALS = (
    "login",
    "session",
    "unauthorized",
    "not logged",
    "authentication",
    "cookie",
    "captcha",
    "verify",
    "challenge",
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _extract_session_id(raw: str) -> Optional[str]:
    raw = raw.strip()
    if not raw:
        return None
    if "=" in raw:
        for part in raw.replace(";", " ").split():
            if part.startswith("sessionid="):
                return part.split("=", 1)[1].strip()
        return None
    return raw


def _write_session_cookies_file(raw_cookie_string: str) -> Path:
    """
    Build a Netscape-format cookies file from a raw cookie string or bare sessionid.

    KEY FIX: TikTok needs more than just sessionid to accept uploads.
    We parse ALL key=value pairs from the cookie string and write each one,
    so tt_csrf_token, sid_guard, uid_tt, etc. are all preserved.
    Domain is written as-is from the source — never force-prefixed with a dot.
    """
    raw = raw_cookie_string.strip()
    tmp = tempfile.NamedTemporaryFile(
        suffix=".txt", prefix="tiktok_cookies_", delete=False,
    )
    lines = [
        b"# Netscape HTTP Cookie File\n",
        b"# Generated by tiktok_poster.py\n\n",
    ]

    # If it looks like a full cookie string (has key=value pairs), parse each one
    if "=" in raw and ";" in raw:
        for part in raw.split(";"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            name, _, value = part.partition("=")
            name = name.strip()
            value = value.strip()
            if name:
                # Use subdomain wildcard for TikTok cookies
                line = f".tiktok.com\tTRUE\t/\tTRUE\t9999999999\t{name}\t{value}\n"
                lines.append(line.encode())
    else:
        # Bare sessionid value — write only sessionid
        session_id = raw
        line = f".tiktok.com\tTRUE\t/\tTRUE\t9999999999\tsessionid\t{session_id}\n"
        lines.append(line.encode())

    for line in lines:
        tmp.write(line)
    tmp.close()
    return Path(tmp.name)


def _build_caption(reel_url: str, views: int, likes: int, extra_tags: list[str]) -> str:
    base_tags = " ".join(f"#{t.lstrip('#')}" for t in Config.TIKTOK_HASHTAGS)
    extra     = " ".join(f"#{t.lstrip('#')}" for t in extra_tags)
    tags_line = f"{base_tags} {extra}".strip()

    template = Config.TIKTOK_CAPTION_TEMPLATE
    if template:
        caption = (
            template
            .replace("{url}", reel_url)
            .replace("{views}", f"{views:,}")
            .replace("{likes}", f"{likes:,}")
            .replace("{tags}", tags_line)
        )
    else:
        caption = f"🎬 {tags_line}"

    return caption[:2200]


def _is_auth_error(exc: Exception) -> bool:
    """Return True if the exception looks like a TikTok auth/session failure."""
    msg = str(exc).lower()
    return any(signal in msg for signal in _AUTH_ERROR_SIGNALS)


# ─────────────────────────────────────────────────────────────────────────────
# TikTokPoster
# ─────────────────────────────────────────────────────────────────────────────

class TikTokPoster:

    def __init__(self) -> None:
        self.enabled: bool = Config.TIKTOK_ENABLED
        self._cookies_path: Optional[Path] = None
        self._temp_cookies: Optional[Path] = None
        self._auth_mode: str = Config.TIKTOK_AUTH_MODE
        self._cleanup_done: bool = False

        if not self.enabled:
            log.info("TikTok posting disabled (TIKTOK_ENABLED=false).")
            return

        if not _uploader_available:
            log.error(
                "tiktok-uploader is not installed — TikTok posting disabled. "
                "Run: pip install tiktok-uploader"
            )
            self.enabled = False
            return

        if (
            (Config.TIKTOK_SESSION_COOKIES.strip() or Config.TIKTOK_SESSION_ID.strip())
            and self._auth_mode == "cookies"
            and not Path(Config.TIKTOK_COOKIES_FILE).exists()
        ):
            log.info(
                "Session cookie value is set and no cookies file found — "
                "switching to session auth mode automatically."
            )
            self._auth_mode = "session"

        self._cookies_path = self._resolve_cookies()
        if not self._cookies_path:
            log.warning(
                "No TikTok cookies configured "
                "(set TIKTOK_COOKIES_FILE or TIKTOK_SESSION_ID) — "
                "TikTok posting disabled."
            )
            self.enabled = False
            return

        log.info(
            f"TikTokPoster ready (auth_mode={self._auth_mode}, "
            f"cookies={self._cookies_path})"
        )

    def __del__(self) -> None:
        self.close()

    def close(self) -> None:
        if self._cleanup_done:
            return
        self._cleanup_done = True
        if self._temp_cookies and self._temp_cookies.exists():
            try:
                self._temp_cookies.unlink()
            except OSError:
                pass

    # ── Auth ──────────────────────────────────────────────────────────────────

    def _resolve_cookies(self) -> Optional[Path]:
        mode = self._auth_mode.lower()

        if mode == "session":
            raw = (Config.TIKTOK_SESSION_COOKIES or Config.TIKTOK_SESSION_ID).strip()
            if not raw:
                log.error("TIKTOK_AUTH_MODE=session but TIKTOK_SESSION_COOKIES/TIKTOK_SESSION_ID is empty.")
                return None
            path = _write_session_cookies_file(raw)
            self._temp_cookies = path
            log.info(f"Wrote session-based cookies to {path}")
            return path

        cookies_path = Path(Config.TIKTOK_COOKIES_FILE)
        if not cookies_path.exists():
            log.error(f"TIKTOK_COOKIES_FILE not found: {cookies_path}")
            return None
        return cookies_path

    def _save_cookies(self, ctx) -> Path:
        """
        Dump Playwright context cookies to a Netscape-format temp file.

        KEY FIX: Domain preserved exactly from Playwright — never force a dot prefix.
        The dot-prefix (subdomain wildcard) is only set when the domain already
        starts with a dot, which Playwright does for wildcard cookies automatically.
        """
        raw_cookies = ctx.cookies([
            "https://www.tiktok.com",
            "https://m.tiktok.com",
            "https://tiktok.com",
        ])
        tmp = tempfile.NamedTemporaryFile(
            suffix=".txt", prefix="tiktok_login_cookies_", delete=False
        )
        tmp.write(b"# Netscape HTTP Cookie File\n\n")
        for c in raw_cookies:
            domain = c.get("domain", ".tiktok.com")
            # KEY FIX: respect the original domain — only subdomain-wildcard cookies
            # (already starting with ".") get TRUE for include_subdomains
            include_sub = "TRUE" if domain.startswith(".") else "FALSE"
            secure      = "TRUE" if c.get("secure") else "FALSE"
            _exp        = c.get("expires", -1)
            # KEY FIX: don't revive expired/session cookies with fake timestamps;
            # use a far-future value only for genuinely missing expiry (session cookies)
            if isinstance(_exp, (int, float)) and _exp > 0:
                expires = str(int(_exp))
            else:
                expires = "9999999999"  # session cookie — set far future
            line = (
                f"{domain}\t{include_sub}\t{c['path']}\t"
                f"{secure}\t{expires}\t{c['name']}\t{c['value']}\n"
            )
            tmp.write(line.encode())
        tmp.close()
        self._temp_cookies = Path(tmp.name)
        self._cookies_path = Path(tmp.name)
        log.info(f"TikTok cookies saved to {tmp.name}")
        return Path(tmp.name)

    def _validate_session(self) -> bool:
        """
        FIX 6 — Deep session validation before every upload.

        Three-stage check:
          Stage 1 — For You page: fast login gate (redirect → dead session).
          Stage 2 — Upload page probe: navigate to /upload, check for captcha,
                    invisible challenges, and upload-ban indicators.  This catches
                    soft account restrictions that the avatar/button check misses.
          Stage 3 — DOM signal scan: explicit check for restriction banners,
                    captcha overlays, and challenge modals on the upload page.

        Returns True only if all stages pass.  Errors inside the validator
        are non-fatal — we return True so a transient validator crash doesn't
        permanently block all uploads.
        """
        try:
            from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

            log.info("TikTok: running deep session validation (3-stage)...")
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                ctx = browser.new_context(
                    user_agent=(
                        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/124.0.0.0 Safari/537.36"
                    )
                )

                # Load cookies into context
                if self._cookies_path and self._cookies_path.exists():
                    try:
                        import http.cookiejar as cj_mod
                        jar = cj_mod.MozillaCookieJar()
                        jar.load(str(self._cookies_path), ignore_discard=True, ignore_expires=True)
                        pw_cookies = [
                            {
                                "name": c.name, "value": c.value,
                                "domain": c.domain, "path": c.path,
                                "secure": bool(c.secure),
                            }
                            for c in jar
                        ]
                        if pw_cookies:
                            ctx.add_cookies(pw_cookies)
                    except Exception as e:
                        log.debug(f"Session validation cookie load warning: {e}")

                page = ctx.new_page()

                # ── Stage 1: For You page login gate ──────────────────────────
                try:
                    page.goto("https://www.tiktok.com/foryou", wait_until="domcontentloaded", timeout=20_000)
                    time.sleep(2)
                    current_url = page.url
                    if "login" in current_url or "signin" in current_url:
                        log.warning("TikTok stage-1 FAILED — redirected to login page.")
                        browser.close()
                        return False
                except PWTimeout:
                    log.warning("TikTok stage-1 timed out.")
                    browser.close()
                    return False

                # Check basic login signals (avatar / upload button)
                logged_in = False
                for sel in [
                    "[data-e2e='nav-profile']",
                    "button[data-e2e='upload-icon']",
                    "[class*='avatar']",
                    "[data-e2e='user-avatar']",
                    "a[href*='/upload']",
                ]:
                    try:
                        el = page.query_selector(sel)
                        if el and el.is_visible():
                            logged_in = True
                            break
                    except Exception:
                        pass

                if not logged_in:
                    log.warning("TikTok stage-1 uncertain — no avatar/upload button found.")
                    browser.close()
                    return False

                log.info("TikTok stage-1 passed ✅ — probing upload page...")

                # ── Stage 2: Upload page probe (FIX 6 core) ───────────────────
                # Navigate to the upload creation page and check if it loads
                # normally.  A soft ban or upload restriction typically manifests
                # as a redirect, a blank page, or a challenge modal here —
                # not on the For You feed.
                try:
                    page.goto("https://www.tiktok.com/upload", wait_until="domcontentloaded", timeout=25_000)
                    time.sleep(random.uniform(2.5, 4.0))  # FIX 2: humanise timing
                    upload_url = page.url

                    # Redirect to login from upload page = hard ban or expired session
                    if "login" in upload_url or "signin" in upload_url:
                        log.warning("TikTok stage-2 FAILED — upload page redirected to login.")
                        browser.close()
                        return False

                    # Redirect to main feed from upload page = upload ban
                    if upload_url.rstrip("/") in (
                        "https://www.tiktok.com",
                        "https://www.tiktok.com/foryou",
                        "https://www.tiktok.com/following",
                    ):
                        log.warning(
                            f"TikTok stage-2 FAILED — upload page redirected to feed "
                            f"({upload_url}) which typically indicates an upload ban."
                        )
                        browser.close()
                        return False

                except PWTimeout:
                    log.warning("TikTok stage-2 upload page timed out — treating as uncertain (pass).")
                    # Don't hard-fail on a slow load — might just be network lag
                    browser.close()
                    return True

                # ── Stage 3: DOM restriction / captcha scan ────────────────────
                # Look for explicit challenge/captcha/ban signals on the upload page.
                restriction_selectors = [
                    # Captcha overlays
                    "[class*='captcha']",
                    "[id*='captcha']",
                    "[data-e2e*='captcha']",
                    # Challenge / verification modals
                    "[class*='verify']",
                    "[class*='challenge']",
                    # Ban / restriction banners
                    "[class*='restrict']",
                    "[class*='violation']",
                    "[class*='suspended']",
                    # Generic error modal that blocks upload
                    ".error-container",
                    "[data-e2e='error-modal']",
                ]
                for sel in restriction_selectors:
                    try:
                        el = page.query_selector(sel)
                        if el and el.is_visible():
                            text = ""
                            try:
                                text = el.inner_text()[:200]
                            except Exception:
                                pass
                            log.warning(
                                f"TikTok stage-3 FAILED — restriction/captcha element "
                                f"detected: {sel!r}  text={text!r}"
                            )
                            browser.close()
                            return False
                    except Exception:
                        pass

                browser.close()
                log.info("TikTok session validation passed all 3 stages ✅")
                return True

        except Exception as exc:
            log.warning(f"TikTok session validation error (non-fatal, skipping check): {exc}")
            return True  # validator crash must not block uploads

    def _do_upload(self, video_path: Path, caption: str) -> None:
        # FIX 2 — Randomized upload timing.
        # TikTok detects robotic upload patterns by measuring entropy in:
        #   • Time between page load and first interaction
        #   • Time between file selection and submit
        #   • Mouse movement / scroll behaviour within the upload page
        # Adding randomized pre-upload waits and a post-submit stabilization
        # pause makes the timing distribution look like a real user.
        pre_wait = random.uniform(2.5, 8.0)
        log.info(f"[TikTok] Pre-upload human timing delay: {pre_wait:.1f}s")
        time.sleep(pre_wait)

        upload_video(
            filename=str(video_path),
            description=caption,
            cookies=str(self._cookies_path),
            headless=Config.TIKTOK_HEADLESS,
            schedule=None,
        )

        # Post-upload stabilization: give TikTok's processing pipeline time to
        # register the submission before we close the browser context.
        post_wait = random.uniform(3.0, 7.0)
        log.info(f"[TikTok] Post-upload stabilization delay: {post_wait:.1f}s")
        time.sleep(post_wait)

    def _push_cookies_to_github_secret(self, cookie_path: Path) -> None:
        import base64
        import json
        import urllib.request
        import urllib.error

        gh_token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
        repo     = os.environ.get("GITHUB_REPOSITORY", "")

        if not gh_token or not repo:
            log.warning(
                "[TikTok] _push_cookies_to_github_secret: "
                "GH_TOKEN or GITHUB_REPOSITORY not set — skipping secret update."
            )
            return

        try:
            cookie_b64 = base64.b64encode(cookie_path.read_bytes()).decode()
        except OSError as exc:
            log.warning(f"[TikTok] Could not read cookie file for secret push: {exc}")
            return

        try:
            pk_url = f"https://api.github.com/repos/{repo}/actions/secrets/public-key"
            req = urllib.request.Request(
                pk_url,
                headers={
                    "Authorization": f"Bearer {gh_token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                pk_data = json.loads(resp.read())
            key_id    = pk_data["key_id"]
            pub_key_b = base64.b64decode(pk_data["key"])

            try:
                from nacl.public import PublicKey, SealedBox  # type: ignore
            except ImportError:
                log.warning("[TikTok] PyNaCl not installed — cannot encrypt secret.")
                return

            encrypted = base64.b64encode(
                SealedBox(PublicKey(pub_key_b)).encrypt(cookie_b64.encode())
            ).decode()

            secret_url = f"https://api.github.com/repos/{repo}/actions/secrets/TIKTOK_COOKIES"
            payload = json.dumps({"encrypted_value": encrypted, "key_id": key_id}).encode()
            put_req = urllib.request.Request(
                secret_url, data=payload, method="PUT",
                headers={
                    "Authorization": f"Bearer {gh_token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                    "Content-Type": "application/json",
                },
            )
            with urllib.request.urlopen(put_req, timeout=15) as resp:
                status = resp.status

            if status in (201, 204):
                log.info("[TikTok] ✅ TIKTOK_COOKIES secret updated in GitHub.")
            else:
                log.warning(f"[TikTok] Secret update returned unexpected status {status}.")

        except urllib.error.HTTPError as exc:
            log.warning(f"[TikTok] GitHub API error updating secret: {exc.code} {exc.reason}")
        except Exception as exc:
            log.warning(f"[TikTok] Failed to push cookies to GitHub secret: {exc}")

    def _manual_login_and_save_cookies(self) -> bool:
        email    = Config.TIKTOK_EMAIL.strip()
        password = Config.TIKTOK_PASSWORD.strip()
        if not email or not password:
            log.warning("No TIKTOK_EMAIL/TIKTOK_PASSWORD set — cannot manual login.")
            return False

        log.info("TikTok: attempting manual login via browser...")
        try:
            from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

            with sync_playwright() as p:
                browser = p.chromium.launch(headless=Config.TIKTOK_HEADLESS)
                ctx = browser.new_context(
                    user_agent=(
                        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/124.0.0.0 Safari/537.36"
                    )
                )
                page = ctx.new_page()

                log.info("TikTok login: navigating directly to email login page...")
                page.goto(
                    "https://www.tiktok.com/login/phone-or-email/email",
                    wait_until="domcontentloaded",
                    timeout=30_000,
                )
                time.sleep(3)

                log.info("TikTok login: filling email...")
                try:
                    page.wait_for_selector(
                        "input[name='username'], input[autocomplete='username'], "
                        "input[type='text']:not([type='password'])",
                        timeout=12_000,
                    )
                    page.fill(
                        "input[name='username'], input[autocomplete='username'], "
                        "input[type='text']:not([type='password'])",
                        email,
                    )
                except PWTimeout:
                    log.error("TikTok login: email input not found.")
                    try:
                        page.screenshot(path="/tmp/tiktok_login_debug.png")
                    except Exception:
                        pass
                    browser.close()
                    return False
                time.sleep(0.5)

                log.info("TikTok login: filling password...")
                page.wait_for_selector("input[type='password']", timeout=8_000)
                page.fill("input[type='password']", password)
                time.sleep(0.5)

                log.info("TikTok login: submitting...")
                page.keyboard.press("Enter")

                log.info("TikTok login: waiting for redirect (captcha/2FA may add delay)...")
                for waited in range(30):
                    time.sleep(1)
                    if "login" not in page.url and "tiktok.com" in page.url:
                        log.info(f"TikTok manual login succeeded after {waited+1}s ✅")
                        cookie_path = self._save_cookies(ctx)
                        browser.close()
                        self._push_cookies_to_github_secret(cookie_path)
                        return True

                log.error(f"TikTok manual login failed after 30s — still on: {page.url}")
                try:
                    page.screenshot(path="/tmp/tiktok_login_failed.png")
                except Exception:
                    pass
                browser.close()
                return False

        except Exception as exc:
            log.error(f"TikTok manual login error: {exc}")
            return False

    def _upload_with_timeout(self, video_path: Path, caption: str) -> None:
        if Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS <= 0:
            self._do_upload(video_path, caption)
            return

        if not hasattr(signal, "SIGALRM"):
            self._do_upload(video_path, caption)
            return

        class _UploadTimeout(Exception):
            pass

        def _handler(_signum, _frame):
            raise _UploadTimeout("TikTok upload timed out")

        old_handler = signal.signal(signal.SIGALRM, _handler)
        try:
            signal.setitimer(signal.ITIMER_REAL, float(Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS))
            self._do_upload(video_path, caption)
        finally:
            try:
                signal.setitimer(signal.ITIMER_REAL, 0)
            except Exception:
                pass
            signal.signal(signal.SIGALRM, old_handler)

    # ── Public API ────────────────────────────────────────────────────────────

    def post(
        self,
        video_path: Path,
        reel_url: str,
        views: int = 0,
        likes: int = 0,
        extra_tags: Optional[list] = None,
    ) -> bool:
        if not self.enabled:
            return False

        if not video_path or not video_path.exists():
            log.error(f"TikTok post skipped — file not found: {video_path}")
            return False

        # KEY FIX: Validate session before the first upload attempt.
        # If the session is dead, try manual re-login once rather than
        # burning all retry slots on doomed upload attempts.
        if not self._validate_session():
            log.warning("[TikTok] Session invalid — attempting manual re-login...")
            if self._manual_login_and_save_cookies():
                log.info("[TikTok] Re-login succeeded; proceeding with upload.")
            else:
                log.error("[TikTok] Re-login failed — skipping upload.")
                return False

        caption = _build_caption(reel_url, views, likes, extra_tags or [])

        for attempt in range(1, Config.TIKTOK_MAX_RETRIES + 1):
            try:
                log.info(
                    f"[TikTok] Upload attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} "
                    f"— {video_path.name}"
                )
                self._upload_with_timeout(video_path, caption)
                log.info(f"[TikTok] ✅ Upload succeeded: {video_path.name}")
                return True

            except Exception as exc:
                # KEY FIX: Auth errors should not be retried — they won't fix
                # themselves and retrying risks triggering a TikTok lockout.
                if _is_auth_error(exc):
                    log.error(
                        f"[TikTok] ❌ Auth error on attempt {attempt} — "
                        f"stopping retries to avoid lockout: {exc}"
                    )
                    return False

                log.warning(
                    f"[TikTok] Upload attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} "
                    f"failed: {exc}"
                )
                if attempt < Config.TIKTOK_MAX_RETRIES:
                    base_sleep = 2 ** attempt
                    jitter = random.uniform(0.5, 2.5)  # FIX 2: jitter prevents robotic retry cadence
                    sleep_s = base_sleep + jitter
                    log.info(f"[TikTok] Retrying in {sleep_s:.1f}s...")
                    time.sleep(sleep_s)

        log.error(
            f"[TikTok] ❌ All {Config.TIKTOK_MAX_RETRIES} upload attempts failed "
            f"for {video_path.name}"
        )
        return False
