#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────────────────
# tiktok_poster.py — TikTok auto-upload
#
# Auth priority (first one that works wins):
#   1. TIKTOK_COOKIES_FILE  — path to a Netscape cookies.txt written by
#                             write_tt_cookies.py (recommended)
#   2. TIKTOK_SESSION_COOKIES / TIKTOK_SESSION_ID  — raw sessionid value or
#                             full semicolon-separated cookie string
#
# Cookie rules:
#   • Domain preserved exactly — NEVER force-add a dot prefix to host-only
#     cookies.  Only bare "tiktok.com" → ".tiktok.com".
#   • Expired cookies SKIPPED — fake far-future timestamps break TikTok auth.
#   • ALL cookies written — TikTok needs tt_csrf_token, sid_guard, uid_tt,
#     etc. in addition to sessionid.
#
# Session validation runs before every upload (3-stage check):
#   Stage 1 — visit /foryou, detect login redirect
#   Stage 2 — visit /upload, detect upload ban / soft restriction
#   Stage 3 — scan DOM for captcha / ban / challenge elements
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import logging
import os
import random
import signal
import tempfile
import time
from pathlib import Path
from typing import Optional

from config import Config

log = logging.getLogger("TikTokPoster")

_uploader_available = False
try:
    from tiktok_uploader.upload import upload_video  # type: ignore
    _uploader_available = True
except ImportError:
    pass

# Errors that mean auth is broken — retrying won't help and risks lockouts
_AUTH_ERROR_SIGNALS = (
    "login", "session", "unauthorized", "not logged",
    "authentication", "cookie", "captcha", "verify", "challenge",
)


# ─────────────────────────────────────────────────────────────────────────────
# Cookie helpers
# ─────────────────────────────────────────────────────────────────────────────

def _fix_tiktok_domain(domain: str) -> str:
    """
    Normalise a TikTok cookie domain.
    Bare 'tiktok.com' (no leading dot, one dot total) → '.tiktok.com'.
    Everything else preserved exactly.
    """
    if not domain:
        return ".tiktok.com"
    if not domain.startswith(".") and domain.count(".") == 1:
        return "." + domain
    return domain


def _write_session_cookies_file(raw: str) -> Path:
    """
    Build a Netscape cookies.txt from a raw cookie string or bare sessionid.

    If raw contains multiple key=value pairs separated by ';', ALL of them
    are written — TikTok needs more than just sessionid (tt_csrf_token,
    sid_guard, uid_tt, etc. must be present too).

    If raw is a bare value with no '=', it is treated as a plain sessionid.
    """
    raw = raw.strip()
    tmp = tempfile.NamedTemporaryFile(
        suffix=".txt", prefix="tiktok_session_", delete=False,
    )
    lines = [
        b"# Netscape HTTP Cookie File\n",
        b"# Generated by tiktok_poster.py\n\n",
    ]

    if "=" in raw:
        # Full cookie string — parse each key=value pair
        for part in raw.split(";"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            name, _, value = part.partition("=")
            name  = name.strip()
            value = value.strip()
            if not name:
                continue
            line = f".tiktok.com\tTRUE\t/\tTRUE\t9999999999\t{name}\t{value}\n"
            lines.append(line.encode())
    else:
        # Bare sessionid value
        line = f".tiktok.com\tTRUE\t/\tTRUE\t9999999999\tsessionid\t{raw}\n"
        lines.append(line.encode())

    for line in lines:
        tmp.write(line)
    tmp.close()
    log.info(f"Wrote session-based cookies to {tmp.name}")
    return Path(tmp.name)


def _save_browser_cookies(ctx, prefix: str = "tiktok_login_") -> Path:
    """
    Dump Playwright context cookies to a Netscape temp file.
    Domain preserved exactly — only cookies already starting with '.' use
    TRUE for include_subdomains.
    """
    raw_cookies = ctx.cookies([
        "https://www.tiktok.com",
        "https://m.tiktok.com",
        "https://tiktok.com",
    ])
    tmp = tempfile.NamedTemporaryFile(suffix=".txt", prefix=prefix, delete=False)
    tmp.write(b"# Netscape HTTP Cookie File\n\n")
    for c in raw_cookies:
        domain      = c.get("domain", ".tiktok.com")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure      = "TRUE" if c.get("secure") else "FALSE"
        exp         = c.get("expires", -1)
        expires     = str(int(exp)) if isinstance(exp, (int, float)) and exp > 0 else "9999999999"
        line = (
            f"{domain}\t{include_sub}\t{c['path']}\t"
            f"{secure}\t{expires}\t{c['name']}\t{c['value']}\n"
        )
        tmp.write(line.encode())
    tmp.close()
    log.info(f"Browser cookies saved to {tmp.name}")
    return Path(tmp.name)


def _push_cookies_to_github(cookie_path: Path) -> None:
    """Best-effort: update the TIKTOK_COOKIES GitHub secret after login."""
    import base64, json, urllib.request, urllib.error
    gh_token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
    repo     = os.environ.get("GITHUB_REPOSITORY", "")
    if not gh_token or not repo:
        log.debug("GH_TOKEN / GITHUB_REPOSITORY not set — skipping secret push.")
        return
    try:
        cookie_b64 = base64.b64encode(cookie_path.read_bytes()).decode()
        pk_req = urllib.request.Request(
            f"https://api.github.com/repos/{repo}/actions/secrets/public-key",
            headers={"Authorization": f"Bearer {gh_token}", "Accept": "application/vnd.github+json",
                     "X-GitHub-Api-Version": "2022-11-28"},
        )
        with urllib.request.urlopen(pk_req, timeout=15) as r:
            pk = json.loads(r.read())
        from nacl.public import PublicKey, SealedBox  # type: ignore
        encrypted = base64.b64encode(
            SealedBox(PublicKey(base64.b64decode(pk["key"]))).encrypt(cookie_b64.encode())
        ).decode()
        put_req = urllib.request.Request(
            f"https://api.github.com/repos/{repo}/actions/secrets/TIKTOK_COOKIES",
            data=json.dumps({"encrypted_value": encrypted, "key_id": pk["key_id"]}).encode(),
            method="PUT",
            headers={"Authorization": f"Bearer {gh_token}", "Accept": "application/vnd.github+json",
                     "X-GitHub-Api-Version": "2022-11-28", "Content-Type": "application/json"},
        )
        with urllib.request.urlopen(put_req, timeout=15) as r:
            log.info(f"TIKTOK_COOKIES secret updated in GitHub (status {r.status}).")
    except Exception as exc:
        log.warning(f"Could not push cookies to GitHub secret: {exc}")


def _build_caption(reel_url: str, views: int, likes: int, extra_tags: list) -> str:
    base_tags = " ".join(f"#{t.lstrip('#')}" for t in Config.TIKTOK_HASHTAGS)
    extra     = " ".join(f"#{t.lstrip('#')}" for t in extra_tags)
    tags_line = f"{base_tags} {extra}".strip()
    template  = Config.TIKTOK_CAPTION_TEMPLATE
    if template:
        caption = (template
                   .replace("{url}",   reel_url)
                   .replace("{views}", f"{views:,}")
                   .replace("{likes}", f"{likes:,}")
                   .replace("{tags}",  tags_line))
    else:
        caption = f"🎬 {tags_line}"
    return caption[:2200]


def _is_auth_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    return any(s in msg for s in _AUTH_ERROR_SIGNALS)


# ─────────────────────────────────────────────────────────────────────────────
# TikTokPoster
# ─────────────────────────────────────────────────────────────────────────────

class TikTokPoster:

    def __init__(self) -> None:
        self.enabled       = Config.TIKTOK_ENABLED
        self._cookies_path: Optional[Path] = None
        self._temp_cookies: Optional[Path] = None
        self._auth_mode    = Config.TIKTOK_AUTH_MODE
        self._cleanup_done = False

        if not self.enabled:
            log.info("TikTok posting disabled (TIKTOK_ENABLED=false).")
            return

        if not _uploader_available:
            log.error("tiktok-uploader not installed — TikTok posting disabled. "
                      "Run: pip install tiktok-uploader")
            self.enabled = False
            return

        # Auto-switch to session mode if a session cookie value is set but no
        # cookies file exists yet (happens on first run before write_tt_cookies.py)
        session_raw = (Config.TIKTOK_SESSION_COOKIES or Config.TIKTOK_SESSION_ID).strip()
        if (session_raw and self._auth_mode == "cookies"
                and not Path(Config.TIKTOK_COOKIES_FILE).exists()):
            log.info("Session cookie set but no cookies file found — switching to session mode.")
            self._auth_mode = "session"

        self._cookies_path = self._resolve_cookies()
        if not self._cookies_path:
            log.warning("No TikTok cookies configured — TikTok posting disabled.")
            self.enabled = False
            return

        log.info(f"TikTokPoster ready (mode={self._auth_mode}, cookies={self._cookies_path})")

    def __del__(self) -> None:
        self.close()

    def close(self) -> None:
        if self._cleanup_done:
            return
        self._cleanup_done = True
        if self._temp_cookies and self._temp_cookies.exists():
            try:
                self._temp_cookies.unlink()
            except OSError:
                pass

    # ── Auth ──────────────────────────────────────────────────────────────────

    def _resolve_cookies(self) -> Optional[Path]:
        if self._auth_mode == "session":
            raw = (Config.TIKTOK_SESSION_COOKIES or Config.TIKTOK_SESSION_ID).strip()
            if not raw:
                log.error("TIKTOK_AUTH_MODE=session but no cookie value set.")
                return None
            path = _write_session_cookies_file(raw)
            self._temp_cookies = path
            return path

        # cookies mode — expect the file written by write_tt_cookies.py
        path = Path(Config.TIKTOK_COOKIES_FILE)
        if not path.exists():
            log.error(
                f"TIKTOK_COOKIES_FILE not found: {path}\n"
                "Make sure write_tt_cookies.py ran successfully and "
                "TIKTOK_COOKIES secret is set in GitHub."
            )
            return None
        return path

    # ── Session validation ────────────────────────────────────────────────────

    def _validate_session(self) -> bool:
        """
        3-stage session check before every upload.
        Errors inside the validator are non-fatal (return True) so a transient
        network glitch doesn't permanently block all uploads.
        """
        try:
            from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
            log.info("TikTok: validating session (3-stage)...")

            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                ctx = browser.new_context(user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
                ))

                # Load cookies
                if self._cookies_path and self._cookies_path.exists():
                    try:
                        import http.cookiejar as cj
                        jar = cj.MozillaCookieJar()
                        jar.load(str(self._cookies_path), ignore_discard=True, ignore_expires=True)
                        pw_cookies = [
                            {"name": c.name, "value": c.value, "domain": c.domain,
                             "path": c.path, "secure": bool(c.secure)}
                            for c in jar
                        ]
                        if pw_cookies:
                            ctx.add_cookies(pw_cookies)
                    except Exception as e:
                        log.debug(f"Validation cookie load: {e}")

                page = ctx.new_page()

                # Stage 1: For You page
                try:
                    page.goto("https://www.tiktok.com/foryou", wait_until="domcontentloaded", timeout=20_000)
                    time.sleep(2)
                    if "login" in page.url or "signin" in page.url:
                        log.warning("Stage 1 FAILED — redirected to login.")
                        browser.close(); return False
                except PWTimeout:
                    log.warning("Stage 1 timed out.")
                    browser.close(); return False

                logged_in = False
                for sel in ["[data-e2e='nav-profile']", "button[data-e2e='upload-icon']",
                            "[class*='avatar']", "[data-e2e='user-avatar']", "a[href*='/upload']"]:
                    try:
                        el = page.query_selector(sel)
                        if el and el.is_visible():
                            logged_in = True; break
                    except Exception:
                        pass
                if not logged_in:
                    log.warning("Stage 1 uncertain — no avatar/upload button found.")
                    browser.close(); return False
                log.info("Stage 1 ✅")

                # Stage 2: Upload page
                try:
                    page.goto("https://www.tiktok.com/upload", wait_until="domcontentloaded", timeout=25_000)
                    time.sleep(random.uniform(2.5, 4.0))
                    url = page.url
                    if "login" in url or "signin" in url:
                        log.warning("Stage 2 FAILED — upload page redirected to login.")
                        browser.close(); return False
                    if url.rstrip("/") in ("https://www.tiktok.com",
                                           "https://www.tiktok.com/foryou",
                                           "https://www.tiktok.com/following"):
                        log.warning(f"Stage 2 FAILED — upload page redirected to feed ({url}), likely upload ban.")
                        browser.close(); return False
                except PWTimeout:
                    log.warning("Stage 2 timed out — treating as uncertain (pass).")
                    browser.close(); return True
                log.info("Stage 2 ✅")

                # Stage 3: DOM restriction scan
                for sel in ["[class*='captcha']", "[id*='captcha']", "[data-e2e*='captcha']",
                            "[class*='verify']", "[class*='challenge']", "[class*='restrict']",
                            "[class*='violation']", "[class*='suspended']",
                            ".error-container", "[data-e2e='error-modal']"]:
                    try:
                        el = page.query_selector(sel)
                        if el and el.is_visible():
                            text = ""
                            try: text = el.inner_text()[:200]
                            except Exception: pass
                            log.warning(f"Stage 3 FAILED — restriction element: {sel!r}  text={text!r}")
                            browser.close(); return False
                    except Exception:
                        pass
                log.info("Stage 3 ✅ — session valid.")
                browser.close()
                return True

        except Exception as exc:
            log.warning(f"Session validation error (non-fatal): {exc}")
            return True

    # ── Manual re-login ───────────────────────────────────────────────────────

    def _manual_login(self) -> bool:
        """
        Email + password login via Playwright.  Only called when session
        validation fails and TIKTOK_EMAIL / TIKTOK_PASSWORD are set.
        Saves fresh cookies after success and pushes them to GitHub secret.
        """
        email    = Config.TIKTOK_EMAIL.strip()
        password = Config.TIKTOK_PASSWORD.strip()
        if not email or not password:
            log.warning("TIKTOK_EMAIL/TIKTOK_PASSWORD not set — cannot re-login.")
            return False

        log.info("TikTok: attempting manual email login...")
        try:
            from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=Config.TIKTOK_HEADLESS)
                ctx = browser.new_context(user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
                ))
                page = ctx.new_page()

                page.goto(
                    "https://www.tiktok.com/login/phone-or-email/email",
                    wait_until="domcontentloaded", timeout=30_000,
                )
                time.sleep(3)

                try:
                    page.wait_for_selector(
                        "input[name='username'], input[autocomplete='username'], "
                        "input[type='text']:not([type='password'])",
                        timeout=12_000,
                    )
                    page.fill(
                        "input[name='username'], input[autocomplete='username'], "
                        "input[type='text']:not([type='password'])",
                        email,
                    )
                except PWTimeout:
                    log.error("TikTok login: email input not found.")
                    try: page.screenshot(path="/tmp/tiktok_login_debug.png")
                    except Exception: pass
                    browser.close()
                    return False

                time.sleep(0.5)
                page.wait_for_selector("input[type='password']", timeout=8_000)
                page.fill("input[type='password']", password)
                time.sleep(0.5)
                page.keyboard.press("Enter")

                log.info("Waiting for redirect (captcha/2FA may delay this)...")
                for waited in range(30):
                    time.sleep(1)
                    if "login" not in page.url and "tiktok.com" in page.url:
                        log.info(f"TikTok login succeeded after {waited+1}s ✅")
                        cookie_path = _save_browser_cookies(ctx)
                        self._temp_cookies = cookie_path
                        self._cookies_path = cookie_path
                        browser.close()
                        _push_cookies_to_github(cookie_path)
                        return True

                log.error(f"TikTok login failed after 30s — still on: {page.url}")
                try: page.screenshot(path="/tmp/tiktok_login_failed.png")
                except Exception: pass
                browser.close()
                return False

        except Exception as exc:
            log.error(f"TikTok manual login error: {exc}")
            return False

    # ── Upload ────────────────────────────────────────────────────────────────

    def _do_upload(self, video_path: Path, caption: str) -> None:
        pre_wait = random.uniform(2.5, 8.0)
        log.info(f"Pre-upload delay: {pre_wait:.1f}s")
        time.sleep(pre_wait)

        upload_video(
            filename=str(video_path),
            description=caption,
            cookies=str(self._cookies_path),
            headless=Config.TIKTOK_HEADLESS,
            schedule=None,
        )

        post_wait = random.uniform(3.0, 7.0)
        log.info(f"Post-upload stabilisation delay: {post_wait:.1f}s")
        time.sleep(post_wait)

    def _upload_with_timeout(self, video_path: Path, caption: str) -> None:
        if Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS <= 0 or not hasattr(signal, "SIGALRM"):
            self._do_upload(video_path, caption)
            return

        class _UploadTimeout(Exception):
            pass

        def _handler(_sig, _frame):
            raise _UploadTimeout("TikTok upload timed out")

        old = signal.signal(signal.SIGALRM, _handler)
        try:
            signal.setitimer(signal.ITIMER_REAL, float(Config.TIKTOK_UPLOAD_TIMEOUT_SECONDS))
            self._do_upload(video_path, caption)
        finally:
            try: signal.setitimer(signal.ITIMER_REAL, 0)
            except Exception: pass
            signal.signal(signal.SIGALRM, old)

    # ── Public API ────────────────────────────────────────────────────────────

    def post(
        self,
        video_path: Path,
        reel_url:   str,
        views:      int = 0,
        likes:      int = 0,
        extra_tags: Optional[list] = None,
    ) -> bool:
        if not self.enabled:
            return False
        if not video_path or not video_path.exists():
            log.error(f"TikTok post skipped — file not found: {video_path}")
            return False

        # Validate session; re-login once if invalid
        if not self._validate_session():
            log.warning("Session invalid — attempting manual re-login...")
            if self._manual_login():
                log.info("Re-login succeeded; proceeding with upload.")
            else:
                log.error("Re-login failed — skipping upload.")
                return False

        caption = _build_caption(reel_url, views, likes, extra_tags or [])

        for attempt in range(1, Config.TIKTOK_MAX_RETRIES + 1):
            try:
                log.info(f"Upload attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} — {video_path.name}")
                self._upload_with_timeout(video_path, caption)
                log.info(f"✅ Upload succeeded: {video_path.name}")
                return True
            except Exception as exc:
                if _is_auth_error(exc):
                    log.error(f"❌ Auth error on attempt {attempt} — stopping retries: {exc}")
                    return False
                log.warning(f"Attempt {attempt}/{Config.TIKTOK_MAX_RETRIES} failed: {exc}")
                if attempt < Config.TIKTOK_MAX_RETRIES:
                    sleep_s = 2 ** attempt + random.uniform(0.5, 2.5)
                    log.info(f"Retrying in {sleep_s:.1f}s...")
                    time.sleep(sleep_s)

        log.error(f"❌ All {Config.TIKTOK_MAX_RETRIES} upload attempts failed for {video_path.name}")
        return False
