"""
Normalise TikTok cookies from the TIKTOK_COOKIES secret into
Netscape tab-separated format expected by agent.py.

The secret may be:
  - A raw Netscape file (tab-separated lines)
  - A JSON array (from a browser cookie-export extension)
  - Either of the above encoded as base64
"""
import os, json, base64

raw = os.environ["TIKTOK_COOKIES"].strip()
out = os.path.expanduser("~/.secrets/tiktok_cookies.txt")

# Try base64-decoding first
try:
    decoded = base64.b64decode(raw).decode("utf-8").strip()
    if decoded.startswith("[") or "tiktok" in decoded.lower():
        raw = decoded
except Exception:
    pass

lines = ["# Netscape HTTP Cookie File", "# Generated by ReelsHunter"]

try:
    cookies = json.loads(raw)
    assert isinstance(cookies, list)
    count = 0
    for c in cookies:
        domain = c.get("domain", ".tiktok.com")
        if not domain.startswith("."): domain = "." + domain
        path   = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        try:    expires = str(int(float(c.get("expirationDate") or c.get("expires") or 2147483647)))
        except: expires = "2147483647"
        name, value = c.get("name", ""), c.get("value", "")
        if name:
            lines.append(f"{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}")
            count += 1
    print(f"TikTok cookies: JSON→Netscape ({count} cookies).")
except Exception:
    lines = raw.splitlines()
    count = sum(1 for l in lines if l and not l.startswith("#") and "\t" in l)
    print(f"TikTok cookies: written as-is ({count} Netscape rows).")

with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
